import { DoctorMedicalRecordDetail } from "../types/medical-record.types";

export const MOCK_DOCTOR_MEDICAL_RECORD_DETAILS: DoctorMedicalRecordDetail[] = [
  {
    id: "record_1",
    recordCode: "PT-9902",
    alertLevel: "MILD_ALLERGY",
    pet: {
      id: "PET-9902",
      code: "PT-9902",
      name: "Lucky",
      species: "Dog",
      breed: "Golden Retriever",
      ageText: "2 tuổi",
      gender: "Đực",
    },
    owner: {
      id: "USR-1001",
      fullName: "Nguyễn Văn A",
      phoneNumber: "0901234567",
      email: "nguyenvana@example.com",
    },
    professionalAlert: {
      title: "LƯU Ý CHUYÊN MÔN",
      description: "Dị ứng với thuốc kháng sinh nhóm Penicillin",
      riskHistory: "Suy thận nhẹ",
    },
    latestExam: {
      id: "EX-9902",
      examCode: "PK-2024-001",
      examinedAt: "2024-10-24",
      veterinarianName: "BS. Trần Văn B",
      examTypeName: "Khám tổng quát",
      diagnosis: "Viêm da gây rụt cấp tính",
      conclusion: "Nhiễm trùng đường ruột nhẹ, cần điều chỉnh chế độ ăn uống.",
      note: "Tiếp tục theo dõi nhiệt độ tại nhà hằng ngày.",
    },
    latestClinicalResult: {
      temperature: "39.2°C",
      weight: "12.5kg",
      heartRate: "120 bpm",
      generalCondition: "Mệt mỏi, lờ đờ",
      skinCoat: "Bình thường",
      respiratory: "Nhịp thở nhanh nhẹ",
      digestive: "Đau bụng khi sờ nắn",
    },
    recentExamHistory: [
      {
        id: "EX-9902",
        examCode: "PK-2024-001",
        examinedAt: "2024-10-24",
        examTypeName: "Khám tổng quát",
        diagnosis: "Viêm da gây rụt cấp tính",
      },
      {
        id: "EX-9801",
        examCode: "PK-2024-000",
        examinedAt: "2024-09-12",
        examTypeName: "Khám da liễu",
        diagnosis: "Dị ứng thức ăn nhẹ",
      },
    ],
  },
  {
    id: "record_2",
    recordCode: "PT-8810",
    alertLevel: "NONE",
    pet: {
      id: "PET-8810",
      code: "PT-8810",
      name: "Milo",
      species: "Cat",
      breed: "Mèo Anh lông ngắn",
      ageText: "3 tuổi",
      gender: "Đực",
    },
    owner: {
      id: "USR-1002",
      fullName: "Trần Minh Tú",
      phoneNumber: "0912345678",
      email: "tranminhtu@example.com",
    },
    latestExam: {
      id: "EX-8810",
      examCode: "PK-2024-018",
      examinedAt: "2024-10-18",
      veterinarianName: "BS. Trần Văn B",
      examTypeName: "Khám định kỳ",
      diagnosis: "Khám định kỳ",
      conclusion: "Thể trạng ổn định, không phát hiện dấu hiệu bất thường.",
      note: "Duy trì lịch tiêm phòng và kiểm tra định kỳ.",
    },
    latestClinicalResult: {
      temperature: "38.4°C",
      weight: "4.8kg",
      heartRate: "145 bpm",
      generalCondition: "Tỉnh táo, phản xạ tốt",
      skinCoat: "Lông bóng, da sạch",
      respiratory: "Bình thường",
      digestive: "Ăn uống ổn định",
    },
    recentExamHistory: [
      {
        id: "EX-8810",
        examCode: "PK-2024-018",
        examinedAt: "2024-10-18",
        examTypeName: "Khám định kỳ",
        diagnosis: "Khám định kỳ",
      },
      {
        id: "EX-8714",
        examCode: "PK-2024-012",
        examinedAt: "2024-08-22",
        examTypeName: "Tiêm phòng",
        diagnosis: "Tiêm nhắc vaccine tổng hợp",
      },
    ],
  },
  {
    id: "record_3",
    recordCode: "PT-7741",
    alertLevel: "MONITORING",
    pet: {
      id: "PET-7741",
      code: "PT-7741",
      name: "Luna",
      species: "Dog",
      breed: "Poodle",
      ageText: "1.5 tuổi",
      gender: "Cái",
    },
    owner: {
      id: "USR-1003",
      fullName: "Phạm Hùng",
      phoneNumber: "0987654321",
      email: "phamhung@example.com",
    },
    professionalAlert: {
      title: "LƯU Ý CHUYÊN MÔN",
      description: "Theo dõi quá trình lành thương sau điều trị",
    },
    latestExam: {
      id: "EX-7741",
      examCode: "PK-2024-015",
      examinedAt: "2024-10-15",
      veterinarianName: "BS. Trần Văn B",
      examTypeName: "Tái khám",
      diagnosis: "Tái khám vết thương",
      conclusion: "Vết thương khô, giảm sưng, chưa có dấu hiệu nhiễm trùng.",
      note: "Giữ vùng da sạch, tái khám sau 7 ngày nếu còn đỏ.",
    },
    latestClinicalResult: {
      temperature: "38.8°C",
      weight: "5.6kg",
      heartRate: "132 bpm",
      generalCondition: "Nhanh nhẹn",
      skinCoat: "Vết thương khô",
      respiratory: "Bình thường",
      digestive: "Bình thường",
    },
    recentExamHistory: [
      {
        id: "EX-7741",
        examCode: "PK-2024-015",
        examinedAt: "2024-10-15",
        examTypeName: "Tái khám",
        diagnosis: "Tái khám vết thương",
      },
      {
        id: "EX-7609",
        examCode: "PK-2024-009",
        examinedAt: "2024-10-01",
        examTypeName: "Khám ngoại khoa",
        diagnosis: "Vết thương mô mềm",
      },
    ],
  },
  {
    id: "record_4",
    recordCode: "PT-6620",
    alertLevel: "NONE",
    pet: {
      id: "PET-6620",
      code: "PT-6620",
      name: "Bé Miu",
      species: "Cat",
      breed: "Mèo ta",
      ageText: "8 tháng",
      gender: "Cái",
    },
    owner: {
      id: "USR-1004",
      fullName: "Lê Văn Khoa",
      phoneNumber: "0934567890",
      email: "levankhoa@example.com",
    },
    latestExam: {
      id: "EX-6620",
      examCode: "PK-2024-012",
      examinedAt: "2024-10-12",
      veterinarianName: "BS. Trần Văn B",
      examTypeName: "Theo dõi tiêu hóa",
      diagnosis: "Theo dõi tiêu hóa",
      conclusion: "Triệu chứng tiêu hóa giảm, ăn uống khá hơn.",
      note: "Chia nhỏ khẩu phần ăn trong 3 ngày tiếp theo.",
    },
    latestClinicalResult: {
      temperature: "38.6°C",
      weight: "2.9kg",
      heartRate: "150 bpm",
      generalCondition: "Tỉnh táo",
      skinCoat: "Bình thường",
      respiratory: "Bình thường",
      digestive: "Phân mềm, giảm nôn",
    },
    recentExamHistory: [
      {
        id: "EX-6620",
        examCode: "PK-2024-012",
        examinedAt: "2024-10-12",
        examTypeName: "Theo dõi tiêu hóa",
        diagnosis: "Theo dõi tiêu hóa",
      },
    ],
  },
];
