import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes.js";
import { groomingRouter } from "../modules/grooming/grooming.routes.js";
import { healthRouter } from "../modules/health/health.routes.js";
import { petsRouter } from "../modules/pets/pets.routes.js";
import { uploadsRouter } from "../modules/uploads/uploads.routes.js";
import { invoicesRouter } from "../modules/invoices/invoices.routes.js";
import { appointmentsRouter } from "../modules/appointments/appointments.routes.js";
import { boardingRouter } from "../modules/boarding/boarding.routes.js";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes.js";
import { followUpsRouter } from "../modules/follow-ups/follow-ups.routes.js";
import { prescriptionsRouter } from "../modules/prescriptions/prescriptions.routes.js";
import { usersRouter } from "../modules/users/users.routes.js";
import { medicinesRouter } from "../modules/medicines/medicines.routes.js";
import { reportsRouter } from "../modules/reports/reports.routes.js";
import { serviceCategoriesRouter } from "../modules/service-categories/service-categories.routes.js";
import { notificationsRouter } from "../modules/notifications/notifications.routes.js";

export const apiRouter = Router();

apiRouter.use(authRouter);
apiRouter.use(healthRouter);
apiRouter.use(groomingRouter);
apiRouter.use(petsRouter);
apiRouter.use(uploadsRouter);
apiRouter.use(invoicesRouter);
apiRouter.use(appointmentsRouter);
apiRouter.use(prescriptionsRouter);
apiRouter.use(followUpsRouter);
apiRouter.use(boardingRouter);
apiRouter.use(dashboardRouter);
apiRouter.use(usersRouter);
apiRouter.use(medicinesRouter);
apiRouter.use(reportsRouter);
apiRouter.use(serviceCategoriesRouter);
apiRouter.use(notificationsRouter);
