import { OwnerInvoice, OwnerInvoiceDetail } from "../types/invoice.types";

export const MOCK_OWNER_INVOICES: OwnerInvoice[] = [
  {
    id: "INV-2024-001",
    invoiceCode: "INV-2024-001",
    title: "Spa & Cắt tỉa",
    pet: {
      id: "PET-001",
      name: "Lucky",
    },
    serviceType: "GROOMING",
    serviceName: "Spa",
    issuedAt: "2023-09-25",
    paymentOption: "AT_COUNTER",
    paymentStatus: "PAID",
    invoiceStatus: "PAID",
    totalAmount: 250000,
    currency: "VND",
  },
  {
    id: "INV-2024-002",
    invoiceCode: "INV-2024-002",
    title: "Tắm gội cơ bản",
    pet: {
      id: "PET-002",
      name: "Bé Bông",
    },
    serviceType: "GROOMING",
    serviceName: "Spa",
    issuedAt: "2023-10-05",
    paymentOption: "ONLINE",
    paymentStatus: "PAID",
    invoiceStatus: "PAID",
    totalAmount: 180000,
    currency: "VND",
  },
  {
    id: "INV-2024-003",
    invoiceCode: "INV-2024-003",
    title: "Lưu trú phòng VIP",
    pet: {
      id: "PET-001",
      name: "Lucky",
    },
    serviceType: "BOARDING",
    serviceName: "Lưu trú",
    issuedAt: "2023-11-15",
    paymentOption: "ONLINE",
    paymentStatus: "PAID",
    invoiceStatus: "PAID",
    totalAmount: 350000,
    currency: "VND",
  },
  {
    id: "INV-2024-004",
    invoiceCode: "INV-2024-004",
    title: "Lưu trú phòng tiêu chuẩn",
    pet: {
      id: "PET-003",
      name: "Milo",
    },
    serviceType: "BOARDING",
    serviceName: "Lưu trú",
    issuedAt: "2023-11-18",
    paymentOption: "AT_COUNTER",
    paymentStatus: "PENDING_PAYMENT",
    invoiceStatus: "PENDING_PAYMENT",
    totalAmount: 220000,
    currency: "VND",
  },
];

export const MOCK_OWNER_INVOICE_DETAILS: OwnerInvoiceDetail[] = [
  {
    ...MOCK_OWNER_INVOICES[0],
    serviceName: "Spa & Cắt tỉa",
    subtotalAmount: 250000,
    discountAmount: 0,
    surchargeAmount: 0,
    note: "Hóa đơn đã được thanh toán thành công.",
  },
  {
    ...MOCK_OWNER_INVOICES[1],
    serviceName: "Tắm gội cơ bản",
    subtotalAmount: 180000,
    discountAmount: 0,
    surchargeAmount: 0,
    note: "Hóa đơn đã được thanh toán thành công.",
  },
  {
    ...MOCK_OWNER_INVOICES[2],
    serviceName: "Lưu trú phòng VIP",
    subtotalAmount: 350000,
    discountAmount: 0,
    surchargeAmount: 0,
    note: "Hóa đơn đã được thanh toán thành công.",
  },
  {
    ...MOCK_OWNER_INVOICES[3],
    serviceName: "Lưu trú phòng tiêu chuẩn",
    subtotalAmount: 220000,
    discountAmount: 0,
    surchargeAmount: 0,
    note: "Vui lòng thanh toán tại trung tâm.",
  },
];
