import request from "supertest";
import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { app } from "../../../src/app.js";
import { cleanupIntegrationTestData, integrationTestIds, seedClinicalIntegrationTestData } from "../helpers/integration-test-db.js";
import { loginAsDoctor, loginAsOwner } from "../helpers/integration-test-auth.js";

describe("clinical and pet history happy path integration", () => {
  beforeEach(seedClinicalIntegrationTestData); afterAll(cleanupIntegrationTestData);
  it("INTX-CLINICAL-149 - owner lists pet medical exams", async () => { const t=await loginAsOwner(); const r=await request(app).get(`/api/v1/pets/${integrationTestIds.petId}/medical-exams`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data).toEqual(expect.arrayContaining([expect.objectContaining({ examId: integrationTestIds.clinicalExamId })])); });
  it("INTX-CLINICAL-152 - owner gets pet medical exam detail", async () => { const t=await loginAsOwner(); const r=await request(app).get(`/api/v1/pets/${integrationTestIds.petId}/medical-exams/${integrationTestIds.clinicalExamId}`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data.examId).toBe(integrationTestIds.clinicalExamId); });
  it("INTX-CLINICAL-155 - owner lists pet vaccinations", async () => { const t=await loginAsOwner(); const r=await request(app).get(`/api/v1/pets/${integrationTestIds.petId}/vaccinations`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data).toEqual(expect.arrayContaining([expect.objectContaining({ vaccinationId: integrationTestIds.vaccinationId })])); });
  it("INTX-CLINICAL-158 - owner lists pet spa history", async () => { const t=await loginAsOwner(); const r=await request(app).get(`/api/v1/pets/${integrationTestIds.petId}/spa-history`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(Array.isArray(r.body.data)).toBe(true); });
  it("INTX-CLINICAL-161 - doctor lists medical records", async () => { const t=await loginAsDoctor(); const r=await request(app).get("/api/v1/doctor/medical-records").query({ keyword:"Milo Integration" }).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.success).toBe(true); });
  it("INTX-CLINICAL-164 - doctor gets medical record detail", async () => { const t=await loginAsDoctor(); const r=await request(app).get(`/api/v1/doctor/medical-records/${integrationTestIds.petId}`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data.pet.petId).toBe(integrationTestIds.petId); });
  it("INTX-CLINICAL-167 - doctor lists prescriptions", async () => { const t=await loginAsDoctor(); const r=await request(app).get("/api/v1/doctor/prescriptions").set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data).toEqual(expect.arrayContaining([expect.objectContaining({ prescriptionId: integrationTestIds.prescriptionId })])); });
  it("INTX-CLINICAL-170 - doctor gets prescription detail", async () => { const t=await loginAsDoctor(); const r=await request(app).get(`/api/v1/doctor/prescriptions/${integrationTestIds.prescriptionId}`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data.prescriptionId).toBe(integrationTestIds.prescriptionId); });
  it("INTX-CLINICAL-173 - doctor lists follow-ups", async () => { const t=await loginAsDoctor(); const r=await request(app).get("/api/v1/doctor/follow-ups").set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data).toEqual(expect.arrayContaining([expect.objectContaining({ followUpId: integrationTestIds.followUpId })])); });
  it("INTX-CLINICAL-176 - doctor gets follow-up detail", async () => { const t=await loginAsDoctor(); const r=await request(app).get(`/api/v1/doctor/follow-ups/${integrationTestIds.followUpId}`).set("Authorization",`Bearer ${t}`); expect(r.status).toBe(200); expect(r.body.data.followUpId).toBe(integrationTestIds.followUpId); });
});
